"""empty message

Revision ID: 2124dd92ca72
Revises: 3aca299a71ed
Create Date: 2020-08-06 20:31:57.900062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2124dd92ca72'
down_revision = '3aca299a71ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('facebook_link', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('facebook_link', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('image_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'image_link')
    op.drop_column('Venue', 'facebook_link')
    op.drop_column('Artist', 'facebook_link')
    # ### end Alembic commands ###
