"""empty message

Revision ID: 3aca299a71ed
Revises: 72f5d99ebe2f
Create Date: 2020-08-06 20:31:45.531561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aca299a71ed'
down_revision = '72f5d99ebe2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'facebook_link')
    op.drop_column('Venue', 'facebook_link')
    op.drop_column('Venue', 'image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
