"""empty message

Revision ID: 691b19ef35e9
Revises: 1b3e757d8bd4
Create Date: 2020-08-04 14:55:25.093459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691b19ef35e9'
down_revision = '1b3e757d8bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
