"""empty message

Revision ID: f58d9b4652e2
Revises: 2e44f11be436
Create Date: 2020-08-04 13:51:57.603289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58d9b4652e2'
down_revision = '2e44f11be436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
